#! /usr/bin/env python2

def options(opt):
    pass

def configure(cfg):
    pass

def build(bld):
    bld.shlib(
        source = '''
            src/rules.cc
            src/entry.cc
            src/interface.cc
            src/api.cc
            src/action-play.cc
            src/game-state.cc
        ''',
        defines = ['MODULE_COLOR=ANSI_COL_BROWN', 'MODULE_NAME="rules"'],
        target = 'tictactoe',
        use = ['net', 'rules', 'utils'],
    )

    bld.install_files('${PREFIX}/share/stechec2/tictactoe', [
        'tictactoe.yml',
        'tictactoe.cfg',
    ])
