#! /usr/bin/env python2

from waflib import Utils

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen(
        features = "subst",
        source= "master-node.in",
        target= "master-node",
        prefix = bld.env.PREFIX
    )
    bld.new_task_gen(
        features = "subst",
        source= "paths.py.in",
        target= "paths.py",
        prefix = bld.env.PREFIX,
        sysconfdir = bld.env.PREFIX + '/share/stechec2/master-node'
    )
    bld.new_task_gen(
        features = "subst",
        source= "master-node.yml.in",
        target= "master-node.yml",
        available_games = ','.join(bld.env.GAMES),
    )
    bld.install_files('${PREFIX}/lib/stechec2/master-node', [
        'paths.py',
        '__init__.py',
        '__main__.py',
        'task.py',
        'utils.py',
        'worker.py',
    ])
    bld.install_files('${PREFIX}/share/stechec2/master-node', ['master-node.yml'])
    bld.install_files('${PREFIX}/bin', ['master-node'], chmod=Utils.O755)
