#! /usr/bin/env python2

from waflib import Utils

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    package = ""
    bld.new_task_gen (
        features = "subst",
        source= "master-node.in",
        target= "master-node",
        PYTHON = "/usr/bin/python",
        prefix = bld.env.PREFIX,
        PACKAGE = package)
    bld.new_task_gen (
        features = "subst",
        source= "paths.py.in",
        target= "paths.py",
        prefix = bld.env.PREFIX,
        PACKAGE = package,
        sysconfdir = bld.env.PREFIX + '/share/master-node')
    bld.new_task_gen (
        features = "subst",
        source= "master-node.yml.in",
        target= "master-node.yml",
        contest = bld.env.GAMES[0])
    bld.install_files('${PREFIX}/lib/master-node', [
        'paths.py',
        '__init__.py',
        '__main__.py',
        'task.py',
        'utils.py',
        'worker.py',
    ])
    bld.install_files('${PREFIX}/share/master-node', ['master-node.yml'])
    bld.install_files('${PREFIX}/bin', ['master-node'], chmod=Utils.O755)
	
