#! /usr/bin/env python

import glob
import os.path


def options(opt):
    pass


def configure(cfg):
    pass


def build(bld):
    bld.shlib(
        source = '''
            src/rules.cc
            src/entry.cc
            src/interface.cc
            src/api.cc
            src/action_guess.cc
            src/game_state.cc
        ''',
        defines = ['MODULE_COLOR=ANSI_COL_BROWN', 'MODULE_NAME="rules"'],
        target = 'plusminus',
        use = ['stechec2'],
    )

    abs_pattern = os.path.join(bld.path.abspath(), 'src/tests/test-*.cc')
    for test_src in glob.glob(abs_pattern):

        test_name = os.path.split(test_src)[-1]
        test_name = test_name[5:-3]

        # Waf requires a relative path for the source
        src_relpath = os.path.relpath(test_src, bld.path.abspath())

        bld.program(
            features = 'gtest',
            source = src_relpath,
            target = 'plusminus-test-{}'.format(test_name),
            use = ['plusminus', 'stechec2-utils'],
            includes = ['.'],
            defines = ['MODULE_COLOR=ANSI_COL_PURPLE',
                       'MODULE_NAME="plusminus"'],
        )

    bld.install_files('${PREFIX}/share/stechec2/plusminus', [
        'plusminus.yml',
    ])
