{# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2020 Association Prologin <association@prologin.org>
#}
{% extends "includes/Makefile.language.jinja2" %}

{% block lang %}cxx{% endblock %}
{% block champion_files %}champion.cc{% endblock %}
{% block generated_files %}interface.cc api.hh{%endblock %}

{% block extra_flags %}
CPPFLAGS += -MMD -MP
{% endblock %}

{% block extra_rules %}
deps = $(objs:.o=.d)
to_clean += $(deps)
-include $(deps)
{% endblock %}
