#!/usr/bin/env python3

from waflib import Utils


def build(bld):
    bld(
        features='subst',
        source='entrypoint.sh.in',
        target='stechec2-generator',
        chmod=Utils.O755,
    )

    bld.install_files('${PREFIX}/bin', ['stechec2-generator'],
                      chmod=Utils.O755)

    # TODO: This is probably the worst possible way to install a Python
    # package. If anyone knows how to just... use a setup.py or something,
    # please tell me how.

    bld.install_files('${PREFIX}/lib/stechec2/generator',
                      (bld.path.ant_glob('**/*.py')
                       + bld.path.ant_glob('**/*.jinja2')),
                      relative_trick=True)
