#!/usr/bin/env python3

from waflib import Utils


def build(bld):
    bld(
        features='subst',
        source='entrypoint.sh.in',
        target='stechec2-generator',
        chmod=Utils.O755,
    )

    bld.install_files('${PREFIX}/bin', ['stechec2-generator'],
                      chmod=Utils.O755)

    # TODO: This is probably the worst possible way to install a Python
    # package. If anyone knows how to just... use a setup.py or something,
    # please tell me how.

    bld.install_files('${PREFIX}/lib/stechec2/generator', [
        '__init__.py',
        '__main__.py',
        'generator.py',
        'rules.py',
        'sphinxdoc.py',
        'texdoc.py',
    ])

    bld.install_files('${PREFIX}/lib/stechec2/generator/filters', [
        'filters/__init__.py',
        'filters/common.py',
        'filters/c.py',
        'filters/cxx.py',
    ])

    bld.install_files('${PREFIX}/lib/stechec2/generator/templates/rules/src', [
        'templates/rules/src/action_template.cc.jinja2',
        'templates/rules/src/action_template.hh.jinja2',
        'templates/rules/src/actions.hh.jinja2',
        'templates/rules/src/api.cc.jinja2',
        'templates/rules/src/api.hh.jinja2',
        'templates/rules/src/constant.hh.jinja2',
        'templates/rules/src/entry.cc.jinja2',
        'templates/rules/src/game_state.cc.jinja2',
        'templates/rules/src/game_state.hh.jinja2',
        'templates/rules/src/interface.cc.jinja2',
        'templates/rules/src/rules.cc.jinja2',
        'templates/rules/src/rules.hh.jinja2',
    ])
    bld.install_files('${PREFIX}/lib/stechec2/generator/templates/rules', [
        'templates/rules/wscript.jinja2',
    ])

    bld.install_files('${PREFIX}/lib/stechec2/generator/templates/texdoc', [
        'templates/texdoc/apidoc.tex.jinja2',
        'templates/texdoc/useapi.tex.jinja2',
    ])

    bld.install_files('${PREFIX}/lib/stechec2/generator/templates/sphinxdoc', [
        'templates/sphinxdoc/api.rst.jinja2',
    ])
