#! /usr/bin/env python2

from waflib import Utils

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.recurse('generator')
    bld.recurse('worker-node')
    bld.recurse('master-node')
    bld.recurse('www')
    bld.install_files('${PREFIX}/bin', \
        ['stechec2-run.py'], chmod=Utils.O755)
