#! /usr/bin/env python2

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.recurse('generator')
    bld.recurse('worker-node')
    bld.recurse('master-node')
    bld.recurse('www')
