#! /usr/bin/env python2',

from waflib import Utils

def options(opt):
    pass

def configure(conf):
    pass

def build(bld):
    bld.new_task_gen (
        features = "subst",
        source= "settings.py.in",
        target= "settings.py",
        prefix = bld.env.PREFIX,
        contest = bld.env.GAMES[0],
        stechec = bld.env.PREFIX + '/stechec/',
        url = "http://127.0.0.1:8067/",
        nb_player = 2,
        bdd = 'stechec',
        user = 'stechec',
        password = 'prologin',
        server = 'localhost',
        port = 5432
        )
    bld.install_files('${PREFIX}/www/concours/', [
        '__init__.py',
        'manage.py',
        'settings.py',
        'urls.py',
	'tournoi.py'])
    bld.install_files('${PREFIX}/www/concours/stechec', [
        'stechec/admin.py',
        'stechec/models.py',
        'stechec/__init__.py',
        'stechec/urls.py',
        'stechec/views.py',
        'stechec/forms.py'])
    bld.install_files('${PREFIX}/www/concours/stechec/templatetags', [
        'stechec/templatetags/substract.py',
        'stechec/templatetags/__init__.py',
        'stechec/templatetags/paginator.py'])
    bld.install_files('${PREFIX}/www/concours/stechec/templates', [
        'stechec/templates/champions-list.html',
        'stechec/templates/champion-new.html',
        'stechec/templates/master-status.html',
        'stechec/templates/champion-delete.html',
        'stechec/templates/paginator.html',
        'stechec/templates/login.html',
        'stechec/templates/index.html',
        'stechec/templates/match-detail.html',
        'stechec/templates/map-detail.html',
        'stechec/templates/maps-list.html',
        'stechec/templates/champion-detail.html',
        'stechec/templates/map-new.html',
        'stechec/templates/base.html',
        'stechec/templates/match-new.html',
        'stechec/templates/matches-list.html'])
    bld.install_files('${PREFIX}/www/concours/stechec/static/js', [
        'stechec/static/js/jquery-1.5.2.min.js'])
    bld.install_files('${PREFIX}/www/concours/stechec/static/img/', [
        'stechec/static/img/head.png',
        'stechec/static/img/back.png',
        'stechec/static/img/page.png'])
    bld.install_files('${PREFIX}/www/concours/stechec/static/img/jquery-ui/', [
        'stechec/static/img/jquery-ui/ui-icons_222222_256x240.png',
        'stechec/static/img/jquery-ui/ui-icons_ffffff_256x240.png',
        'stechec/static/img/jquery-ui/ui-bg_glass_65_ffffff_1x400.png',
        'stechec/static/img/jquery-ui/ui-bg_highlight-soft_75_ffe45c_1x100.png',
        'stechec/static/img/jquery-ui/ui-bg_gloss-wave_35_f6a828_500x100.png',
        'stechec/static/img/jquery-ui/ui-icons_ef8c08_256x240.png',
        'stechec/static/img/jquery-ui/ui-bg_diagonals-thick_18_b81900_40x40.png',
        'stechec/static/img/jquery-ui/ui-bg_diagonals-thick_20_666666_40x40.png',
        'stechec/static/img/jquery-ui/ui-bg_highlight-soft_100_eeeeee_1x100.png',
        'stechec/static/img/jquery-ui/ui-icons_ffd27a_256x240.png',
        'stechec/static/img/jquery-ui/ui-bg_flat_10_000000_40x100.png',
        'stechec/static/img/jquery-ui/ui-bg_glass_100_f6f6f6_1x400.png',
        'stechec/static/img/jquery-ui/ui-icons_228ef1_256x240.png',
        'stechec/static/img/jquery-ui/ui-bg_glass_100_fdf5ce_1x400.png'])
    bld.install_files('${PREFIX}/www/concours/stechec/static/css/', [
        'stechec/static/css/jquery-ui-1.8.11.css',
        'stechec/static/css/main.css'])
    bld.install_files('${PREFIX}/www/concours/stechec/static/font/', [
        'stechec/static/font/exocet-heavy.ttf'])
    
